stages:
  - build
  - deploy
  
variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

top-level-job:
  stage: build
  script:
    - echo "Hello."

include:
  - local: /frontend/.gitlab-ci.yml
  - local: /lambda/.gitlab-ci.yml