image: python:3.8

stages:
  - build
  - deploy

create_package:
  stage: build
  script:
    - apt-get update && apt-get install -y zip  # Install zip if it's not available
    - cd lambda/layers
    - python -m venv venv  # Create a virtual environment
    - source venv/bin/activate  # Activate the virtual environment
    - pip install -r requirements.txt  # Install dependencies
    - deactivate  # Deactivate the virtual environment
    - mv *.py venv/lib/python3.8/site-packages/  # Move your lambda function to the virtual environment
    - cd venv/lib/python3.8/site-packages && zip -r9 ${CI_PROJECT_DIR}/lambda/layers/function.zip .  # Package the virtual environment
  artifacts:
    paths:
      - lambda/layers/function.zip
    expire_in: 1 hour

upload_to_s3:
  stage: deploy
  image: python:3.8-slim  # Using a slim image for deployment
  script:
    - apt-get update && apt-get install -y awscli  # Install AWS CLI
    - echo $AWS_DEFAULT_REGION  # Optional: Print the AWS region, for debug purposes
    - aws s3 cp lambda/layers/function.zip s3://term-project-lamdas/layer/function.zip  # Upload to S3
  only:
    - main  # Only run this job on the master branch