AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for DynamoDB tables

Resources:
  ChatsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: chats
      AttributeDefinitions:
        - AttributeName: chat_id
          AttributeType: S
      KeySchema:
        - AttributeName: chat_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ConnectionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: connection
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
        - AttributeName: user
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user-index
          KeySchema:
            - AttributeName: user
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  FriendlistTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: friendlist
      AttributeDefinitions:
        - AttributeName: user
          AttributeType: S
      KeySchema:
        - AttributeName: user
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  UserDetailsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: user-details
      AttributeDefinitions:
        - AttributeName: user
          AttributeType: S
      KeySchema:
        - AttributeName: user
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
